In [6]:
import pandas as pd
import numpy as ny
import seaborn as sns
import matplotlib.pyplot as plt

In [161]:
#bank=filename='D://Data Science/Python/worked/bank-full.csv'
bank=pd.read_csv('C://Users/jeysu_000/Data Science/Data/bank.csv',sep =";")
bank.tail()


age           job   marital  education default  balance housing loan  \
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no

In [162]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [174]:
x1=bank.iloc[:,[0,2,3,5,15]].values
#x= pd.DataFrame(x)
y1=bank.iloc[:,-1].values
#z=bank.iloc[:,[15]].values
print (x)

[[58 'married' 'tertiary' 2143 'unknown']
 [44 'single' 'secondary' 29 'unknown']
 [33 'married' 'secondary' 2 'unknown']
 ...
 [72 'married' 'secondary' 5715 'success']
 [57 'married' 'secondary' 668 'unknown']
 [37 'married' 'secondary' 2971 'other']]


In [183]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
x= pd.DataFrame(x)
x_labelencoder = LabelEncoder()
x.iloc[:,1] = x_labelencoder.fit_transform(x.iloc[:,1])
x.iloc[:,2] = x_labelencoder.fit_transform(x.iloc[:,2])
#x.iloc[:,3] = x_labelencoder.fit_transform(x.iloc[:,3])
x.iloc[:,4] = x_labelencoder.fit_transform(x.iloc[:,4])
print(x)

        0  1  2     3  4
0      58  1  2  3036  3
1      44  2  1   945  3
2      33  1  1   918  3
3      47  1  3  2420  3
4      33  2  3   917  3
...    .. .. ..   ... ..
45206  51  1  2  1741  3
45207  71  0  0  2639  3
45208  72  1  1  5455  2
45209  57  1  1  1584  3
45210  37  1  1  3779  1

[45211 rows x 5 columns]


In [184]:
y_labelencoder = LabelEncoder()
y=y_labelencoder.fit_transform(y[:])
print(y)

[0 0 0 ... 1 0 0]


In [68]:
y

array([0, 0, 0, ..., 1, 0, 0])

In [185]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.20, random_state=0)
x_train,x_test,y_train,y_test

(        0  1  2     3  4
 13932  57  0  1  1574  3
 9894   37  1  3  2609  3
 39946  35  0  1  3657  0
 9217   35  1  1  1130  3
 4124   38  2  2  1239  3
 ...    .. .. ..   ... ..
 30403  35  2  2  1911  3
 21243  35  1  2  1666  3
 42613  35  1  2  1239  3
 43567  70  1  1  1532  0
 2732   46  2  1   973  3
 
 [36168 rows x 5 columns],
         0  1  2     3  4
 14001  37  1  2  2319  3
 32046  36  2  1   663  3
 13318  47  1  0   516  3
 42991  57  1  0  1417  0
 14237  33  1  1   516  3
 ...    .. .. ..   ... ..
 18448  53  1  0  1168  3
 6654   28  2  2  2899  3
 17106  28  1  1   923  3
 9025   59  1  1   916  3
 13171  50  1  0   602  3
 
 [9043 rows x 5 columns],
 array([1, 0, 0, ..., 1, 0, 0]),
 array([0, 1, 0, ..., 0, 1, 0]))

In [186]:
#Scalling
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)
x_train,x_test,y_train,y_test

(array([[ 1.51506117, -1.91917636, -0.30097185, -0.26789309,  0.44433241],
        [-0.36959746, -0.27704789,  2.38019807,  0.43667051,  0.44433241],
        [-0.55806332, -1.91917636, -0.30097185,  1.15008369, -2.58671521],
        ...,
        [-0.55806332, -0.27704789,  1.03961311, -0.49594024,  0.44433241],
        [ 2.74008927, -0.27704789, -0.30097185, -0.29648407, -2.58671521],
        [ 0.47849892,  1.36508059, -0.30097185, -0.67701649,  0.44433241]]),
 array([[-0.37504691, -0.27059763,  1.02361062,  0.25851682,  0.44717154],
        [-0.46898783,  1.38167407, -0.29893701, -0.89046345,  0.44717154],
        [ 0.56436234, -0.27059763, -1.62148463, -0.99245626,  0.44717154],
        ...,
        [-1.22051523, -0.27059763, -0.29893701, -0.710068  ,  0.44717154],
        [ 1.69165343, -0.27059763, -0.29893701, -0.7149248 ,  0.44717154],
        [ 0.84618511, -0.27059763, -1.62148463, -0.932787  ,  0.44717154]]),
 array([1, 0, 0, ..., 1, 0, 0]),
 array([0, 1, 0, ..., 0, 1, 0]))

In [187]:
# Model
from sklearn.linear_model import LogisticRegression
rslt=LogisticRegression(random_state=0)
rslt.fit (x_train,y_train)

LogisticRegression(random_state=0)

In [188]:
# Prediction
y_pred=rslt.predict(x_test)
print(y_pred)

[0 0 0 ... 0 0 0]


In [189]:
# Confusion Matrix
results= pd.crosstab(y_test,y_pred, rownames=['Act'], colnames=['Pred'])
print(results)

Pred     0
Act       
0     7980
1     1063


In [190]:
#Model validation
from sklearn.model_selection import cross_val_score
results = rslt.score(x_test, y_test)
print(results*100,'%')Hi Parthik

88.2450514209886 %
