In [1]:
import numpy as np
import math
import pandas as pd


In [13]:
a= np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)], dtype=float)


In [68]:
i=np.array([1,2,3])

In [14]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
b1=np.array([(1.5,2,3),(4,5,6)])

In [12]:
b1

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
#Create an array of evenly spaced values (step value)
d=np.arange(10,25,5)
d

array([10, 15, 20])

In [28]:
np.linspace(0,3,4)

array([0., 1., 2., 3.])

In [31]:
e = np.full((3,2),7)
e

array([[7, 7],
       [7, 7],
       [7, 7]])

In [35]:
f=np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.random.random((2,2))

array([[0.31414568, 0.23443677],
       [0.23634564, 0.27138418]])

In [41]:
np.empty((4,2))

array([[0.375, 0.75 ],
       [1.125, 1.5  ],
       [1.875, 2.25 ],
       [2.625, 3.   ]])

In [43]:
np.savez('save_array',a)

In [44]:
c.shape

(2, 2, 3)

In [52]:
len(np.empty((3,2)))

3

In [53]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [60]:
g=a-b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [62]:
a<b

array([[ True, False, False],
       [ True,  True,  True]])

In [69]:
np.array_equal(a,i)


True

In [79]:
b.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'