In [1]:
#Import Python Libraries
import numpy as np
import pandas as pd
import os


In [3]:
import matplotlib.pyplot as plt

In [4]:
x = [10,21,3,14,15,16]
y = np.array(x)

In [7]:
x

[10, 21, 3, 14, 15, 16]

In [8]:
y

array([10, 21,  3, 14, 15, 16])

In [10]:
y.shape

(6,)

In [12]:
y>10

array([False,  True, False,  True,  True,  True])

In [14]:
y[y>10]

array([21, 14, 15, 16])

In [16]:
y**2

array([100, 441,   9, 196, 225, 256], dtype=int32)

In [17]:
x = [1,2,3,4,5,6]
y = [7,8,9,10,11,12]

In [20]:
z=np.array([x,y])

In [22]:
z

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
z = z.reshape(4,3)

In [34]:
z[0,1]

2

In [32]:
z.shape

(4, 3)

In [35]:
z[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [37]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
np.mean(z)

6.5

In [41]:
np.std(z)

3.452052529534663

In [42]:
np.round(1.2323,2)

1.23